name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TAG: "test"
  IMAGE_NAME: "focus-control-server"
  IMAGE_NAME_TEST: "focus-control-server-test"
  CONTAINER_NAME: "focus-control-server-test"
  PORT: "8081"

jobs:

  build:
    runs-on: test
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          docker build --pull -t $IMAGE_NAME --no-cache .
          
  stop:
    runs-on: test
    needs: [build]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: stop
        run: |
          docker stop $CONTAINER_NAME
          docker rm $CONTAINER_NAME
    
          
  deploy:
    runs-on: test
    needs: [stop]
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: |
          docker tag $IMAGE_NAME $IMAGE_NAME_TEST
          docker run -d --name=$CONTAINER_NAME -p $PORT:8080 $IMAGE_NAME_TEST
        
  clean:
    runs-on: test
    needs: [deploy]
    steps:
      - uses: actions/checkout@v3
      - name: clean
        run: docker system prune -a -f
